### ISSUE TITLE
Stateless 301 or 302 redirect to Twilio

### ISSUE THREAD

**Issue by anotherdevs** [unRob/sip-client#5]
Hi Rob

Can someone please help me setup this script: https://gist.github.com/anotherdevs/c5e62f1de343f83f297e

This script uses sip-client (https://github.com/unRob/sip-client) to create a connection to my REGISTRY.
This REGISTRY is supposed to send calls to my server (this script).

All inbound calls are then supposed to be redirected to Twilio - if possible stateless.

So:

My server connects to my providers SIP-server.
Calls received to my providers SIP-server are redirect to my server.
Call gets redirected from my server to Twilios SIP-server.

Full disclosure:
I've also created a similar issue with sip.js: https://github.com/kirm/sip.js/issues/108

**Comment by anotherdevs** [comment]
Hi @unRob 

Thank you for adding labels

Do you by any chance yourself know how to implement this kind of behaviour?

**Comment by unRob** [comment]
Hi! I'd love to help you, but I just don't know a lot about SIP or how to do call forwarding, and have no way to actually test your setup, nor the time to invest in it (I'm taking my nephews to the park!).

I've tried to implement [this workflow](http://www.vocal.com/sip-2/call-forwarding/), but haven't had much luck. Hope that helps you continue working on your script!

**Comment by anotherdevs** [comment]
Hi @unRob 

Can you guide me how to send status messages (like 100 and 180 and 302)?
